#!/bin/zsh

# system commands
alias du1="du -d 1"
case "$OSTYPE" in
  darwin*)
	alias dus="du -L -d 1 -h 2>/dev/null | gsort -h"
  ;;
  linux*)
  alias dus="du -L -d 1 -h 2>/dev/null | sort -h"
  ;;
esac

# set silver searcher or ripgrep on linux alias
if type "ripgrep" > /dev/null; then
  alias ripgrep="rg"
fi

# fasd aliases for fast directory movement (jj asks for any directory matching a fuzzy search)
if type "fasd" > /dev/null; then
  alias j='fasd_cd -d'
  alias jj='fasd_cd -d -i'
fi

# Force remove and do so for directories too
alias rmf='rm -r -f'

# Remove last line of file
alias lastlineremove="sed -i '' -e '$ d' foo.txt"

# Tmux aliases
if type "tmux" > /dev/null; then
  alias ta='tmux a'
  alias tmd='tmux detach'
fi

# Pip install aliases
alias pipi='pip install'
alias pipe='pip install -e'

# Python aliases
alias pytabtospace="find . -name '*.py' -type f -exec bash -c 'T=$(mktemp); expand -t 8 \"\$0\" > \"\$T\" && mv \"\$T\" \"\$0\"' {} \;"

# Kube Aliases
if type "kubectl" > /dev/null; then
  alias k='kubectl'
fi

# Only shows the number of lines and not the filename
alias wcl='wc -l <'

# Emacs related
if type "emacs" > /dev/null; then
  alias emac="nohup emacs -q --no-desktop -l ${HOME}/Programs/scimax/init.el </dev/null >/dev/null 2>&1 &"
  alias emacautosavefind="find . -iname '#*#' -type f -print"
  alias emacautosavedel="find . -iname '#*#' -type f -delete"
  alias emacdel="find ${HOME}/.emacs_path_backups -mtime +180 -type f -delete"
  alias emacbackprint="find ${HOME}/.emacs_path_backups -mtime +180 -type f -print"
  alias emacbackdel="find ${HOME}/.emacs_path_backups -mtime +180 -type f -delete"
fi

# hub has all the features of git and more for github (alias git=hub if exists)
if type "hub" > /dev/null; then
  eval "$(hub alias -s)"
fi

# Convert pdf
if type "convert" > /dev/null; then
  alias resizepdfzip="convert -compress Zip -density 150x150"
  alias resizepdfjpeg="convert -quality 90 -compress jpeg"
fi

# History commands
alias histread='fc -R'
alias histwrite='fc -W'

# Linux system / graphical interface
alias graphicalstop="sudo systemctl stop gdm3.service"
alias graphicalstart="sudo systemctl start gdm3.service"
alias systemstarttext="sudo systemctl set-default multi-user.target"
alias systemstartgraphical="sudo systemctl set-default graphical.target"

# Apt-get/snap install
alias sai="sudo apt install"
alias snai="sudo snap install"

# END
