#!/bin/zsh

# Necessary to use complete command anywhere
autoload -U +X bashcompinit && bashcompinit

# setup iterm2 shell integrations if iterm terminal
if test -e ${HOME}/.iterm2/it2check && ${HOME}/.iterm2/it2check; then
  # This works if using tmux with -CC, but doesn't work with normal tmux so only set on mac
  if [[ "$OSTYPE" == darwin* ]]; then
	export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=YES
  fi
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

if [[ -s "/usr/local/bin/terraform" ]]; then
  complete -o nospace -C /usr/local/bin/terraform terraform
fi

if [[ -s "${HOME}/.config/broot/launcher/bash/br" ]]; then
  source "${HOME}/.config/broot/launcher/bash/br"
fi
if [[ -s '/usr/local/bin/aws_completer' ]]; then
  complete -C '/usr/local/bin/aws_completer' aws
fi
if type "kubectl" > /dev/null; then
  source <(kubectl completion zsh)
fi

if [[ -s "${HOME}/miniconda3/bin/conda" ]]; then
	__conda_setup="$('${HOME}/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
		eval "$__conda_setup"
	else
		if [ -f "${HOME}/miniconda3/etc/profile.d/conda.sh" ]; then
			. "${HOME}/miniconda3/etc/profile.d/conda.sh"
		else
			export PATH="/Users/spence/miniconda3/bin:$PATH"
		fi
	fi
	unset __conda_setup
fi

if [[ -s "${HOME}/anaconda3/bin/conda" ]]; then
  # >>> conda initialize >>>
  # !! Contents within this block are managed by 'conda init' !!
  __conda_setup="$('${HOME}/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
	  eval "$__conda_setup"
  else
	  if [ -f "${HOME}/anaconda3/etc/profile.d/conda.sh" ]; then
		  . "${HOME}/anaconda3/etc/profile.d/conda.sh"
	  else
		  export PATH="${HOME}/anaconda3/bin:$PATH"
	  fi
  fi
  unset __conda_setup
  # <<< conda initialize <<<
fi

if type "direnv" > /dev/null; then
  eval "$(direnv hook zsh)"
fi

# location where uv is typically installed
if [[ -d $HOME/.local/bin ]]; then
	export PATH="$HOME/.local/bin:$PATH"
fi

if [[ -d $PYENV_ROOT ]]; then
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi

# END
