#!/bin/zsh

# Necessary to use complete command anywhere
autoload -U +X bashcompinit && bashcompinit

# setup iterm2 shell integrations if iterm terminal
if test -e ${HOME}/.iterm2/it2check && ${HOME}/.iterm2/it2check; then
  # This works if using tmux with -CC, but doesn't work with normal tmux so only set on mac
  if [[ "$OSTYPE" == darwin* ]]; then
	export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=YES
  fi
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

if [[ -s "/usr/local/bin/terraform" ]]; then
  complete -o nospace -C /usr/local/bin/terraform terraform
fi

if [[ -s "${HOME}/.config/broot/launcher/bash/br" ]]; then
  source "${HOME}/.config/broot/launcher/bash/br"
fi
if [[ -s '/usr/local/bin/aws_completer' ]]; then
  complete -C '/usr/local/bin/aws_completer' aws
fi
if type "kubectl" > /dev/null; then
  source <(kubectl completion zsh)
fi

if [[ -s "${HOME}/miniconda3/bin/conda" ]]; then
	__conda_setup="$('${HOME}/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
		eval "$__conda_setup"
	else
		if [ -f "${HOME}/miniconda3/etc/profile.d/conda.sh" ]; then
			. "${HOME}/miniconda3/etc/profile.d/conda.sh"
		else
			export PATH="/Users/spence/miniconda3/bin:$PATH"
		fi
	fi
	unset __conda_setup
fi

if [[ -s "${HOME}/anaconda3/bin/conda" ]]; then
  # >>> conda initialize >>>
  # !! Contents within this block are managed by 'conda init' !!
  __conda_setup="$('${HOME}/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
	  eval "$__conda_setup"
  else
	  if [ -f "${HOME}/anaconda3/etc/profile.d/conda.sh" ]; then
		  . "${HOME}/anaconda3/etc/profile.d/conda.sh"
	  else
		  export PATH="${HOME}/anaconda3/bin:$PATH"
	  fi
  fi
  unset __conda_setup
  # <<< conda initialize <<<
fi

if type "direnv" > /dev/null; then
  eval "$(direnv hook zsh)"
fi

# location where uv is typically installed
if [[ -d $HOME/.local/bin ]]; then
	export PATH="$HOME/.local/bin:$PATH"
fi

if [[ -d $PYENV_ROOT ]]; then
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi

if [[ -s "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc" ]]; then
  source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
fi
if [[ -s "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" ]]; then
  source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
fi

export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

export EDITOR='emacsclient --create-frame --alternate-editor="code -w"'
export VISUAL=$EDITOR

# Invoke tab-completion script to be sourced with the Z shell.
# Known to work on zsh 5.0.x, probably works on later 4.x releases as well (as
# it uses the older compctl completion system).

_complete_invoke() {
	# `words` contains the entire command string up til now (including
	# program name).
	#
	# We hand it to Invoke so it can figure out the current context: spit back
	# core options, task names, the current task's options, or some combo.
	#
	# Before doing so, we attempt to tease out any collection flag+arg so we
	# can ensure it is applied correctly.
	collection_arg=''
	if [[ "${words}" =~ "(-c|--collection) [^ ]+" ]]; then
		collection_arg=$MATCH
	fi
	# `reply` is the array of valid completions handed back to `compctl`.
	# Use ${=...} to force whitespace splitting in expansion of
	# $collection_arg
	reply=( $(invoke ${=collection_arg} --complete -- ${words}) )
}

export METAFLOW_USER=jeff
export DEV_EC2_INSTANCE_ID=i-0cf628e7da6c08ab6
export DASHBOARD_EC2_INSTANCE_ID=i-032fe5e234962fb9d

# Stops ctrl+y from suspending processes (ctrl+z still works)
# This is necessary due to using invoke
# Found fix here: https://github.com/jonas/tig/issues/214
stty dsusp undef

if type "thefuck" > /dev/null; then
  eval $(thefuck --alias fuck)
fi


# Tell shell builtin to use the above for completing our given binary name(s).
# * -K: use given function name to generate completions.
# * +: specifies 'alternative' completion, where options after the '+' are only
#   used if the completion from the options before the '+' result in no matches.
# * -f: when function generates no results, use filenames.
# * positional args: program names to complete for.
if type "invoke" > /dev/null; then
  compctl -K _complete_invoke + -f invoke inv
fi

# vim: set ft=sh :

# END
