#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

expand-or-complete-with-dots() {      # This bunch of code displays red dots when autocompleting
  echo -n "\e[31m......\e[0m"         # a command with the tab key, "Oh-my-zsh"-style.
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

#function f() { find . -iname "*$1*" ${@:2} }
#function r() { grep "$1" ${@:2} -R . }

setopt extended_glob
setopt ksh_glob

# Source private.
if [[ -s "${HOME}/.zprivate" ]]; then
  source "${HOME}/.zprivate"
fi

if [[ -s "${HOME}/.zaliases" ]]; then
  source "${HOME}/.zaliases"
fi

# Try to setup to expand aliases
expand-aliases() {
  unset 'functions[_expand-aliases]'
  functions[_expand-aliases]=$BUFFER
  (($+functions[_expand-aliases])) &&
	BUFFER=${functions[_expand-aliases]#$'\t'} &&
	CURSOR=$#BUFFER
}
zle -N expand-aliases
bindkey '\e^E' expand-aliases

# Treat these characters as part of a word.
WORDCHARS='*?[]~&;!#$%^(){}<>'

# Setup basic paths
export PATH=${HOME}/bin:$PATH
export LD_LIBRARY_PATH=${HOME}/lib:$LD_LIBRARY_PATH

# Mac config

export SUBLIME=subl
export EDITOR=$SUBLIME' -w'
export VISUAL=$EDITOR

export PATH=$PATH:$HOME/Dropbox/Programs/system-scripts

# First check if iterm terminal and run shell integration if so
${HOME}/.iterm2/it2check && test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/spence/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/spence/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/spence/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/spence/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
