#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your
# unsetopt CORRECT                      # Disable autocorrect guesses. Happens when typing a wrong
                                      # command that may look like an existing one.

expand-or-complete-with-dots() {      # This bunch of code displays red dots when autocompleting
  echo -n "\e[31m......\e[0m"         # a command with the tab key, "Oh-my-zsh"-style.
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

#function f() { find . -iname "*$1*" ${@:2} }
#function r() { grep "$1" ${@:2} -R . }

setopt extended_glob
setopt ksh_glob

# Even better: use the silver searcher (brew install the_silver_searcher)
alias fs="ag -g"
alias rs=ag
alias su="subl"
alias sn="subl -n"
alias snw="subl -n -w"
alias sb="subl -n -b"
alias snb="subl -n -b"
alias opf="open -a Finder"
alias ema="nohup emacs -q -l /Users/bigtyme/Dropbox/SyncedPrograms/emacs/jmax/init.el &"
# Default aliases for fasd already set but here for reference
# alias fa='fasd -a'        # any
# alias fs='fasd -si'       # show / search / select
alias j='fasd_cd -d'
alias jj='fasd_cd -d -i'
alias fd='fasd -d'        # directory
alias ff='fasd -f'        # file
alias fsd='fasd -sid'     # Interactive directory selection
alias fsf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection
# unalias rm
alias rmi='rm -i'
alias rmd='rm -r'
alias rmir='rm -i -r'
# Used to unalias to use the ghostscript command /usr/local/bin/gs
# unalias gs
# alias gst='git stash'
alias opar='open -a "Adobe Acrobat Reader DC"'
alias jupq='jupyter qtconsole --style monokai'
alias jupqt='jupyter qtconsole --style monokai'
alias jupqe='jupyter qtconsole --style monokai  --existing'
alias ipq='ipython qtconsole --style monokai'
alias ipqt='ipython qtconsole --style monokai'
alias ipqe='ipython qtconsole --style monokai  --existing'
alias unm='diskutil unmountDisk /dev/disk2s1'
alias unmo='diskutil unmountDisk /dev/disk2s1'
alias unmount='diskutil unmountDisk'
alias unmountd='diskutil unmountDisk /dev/disk2s1'
alias kql='killall qlmanage'
alias netoff='networksetup -setairportpower en0 off'
alias neton='networksetup -setairportpower en0 on'
alias netoffon='networksetup -setairportpower en0 off; networksetup -setairportpower en0 on'
alias noo='networksetup -setairportpower en0 off; networksetup -setairportpower en0 on'
alias adp='adb push'
alias td='todo.sh'
alias sl='pmset sleepnow'
# alias sle='pmset sleepnow'
alias pms='pmset sleepnow'
alias getmyip='dig +short myip.opendns.com @resolver1.opendns.com'

# Brew aliases
alias brewski='brew update && brew upgrade && brew cleanup; brew doctor'

# GIT aliases
alias gcof='git checkout -f'
alias gche='git cherry-pick'
alias gpristine='git reset --hard && git clean -df'
alias gpris='git reset --hard && git clean -df'
alias gdt='git difftool --ignore-space-at-eol --ignore-blank-lines -w -b'
alias gau='git add -u'

# alias ls='ls -G -h'
alias lh='ls -h -a'
# alias jupqte='jupyter qtconsole --style monokai --existing'

# Try to setup to expand aliases
expand-aliases() {
  unset 'functions[_expand-aliases]'
  functions[_expand-aliases]=$BUFFER
  (($+functions[_expand-aliases])) &&
    BUFFER=${functions[_expand-aliases]#$'\t'} &&
    CURSOR=$#BUFFER
}
zle -N expand-aliases
bindkey '\e^E' expand-aliases

# Treat these characters as part of a word.
WORDCHARS='*?[]~&;!#$%^(){}<>'

export SUBLIME=subl
export EDITOR=$SUBLIME' -w'
export VISUAL=$EDITOR
export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"
# export PATH=/Users/bigtyme/anaconda/bin:/Users/bigtyme/bin:/usr/local/bin:/usr/local/share/python:$PATH:/Users/bigtyme/Dropbox/Programs/system-scripts
export PATH=/Users/bigtyme/anaconda/bin:/Users/bigtyme/bin:/usr/local/bin:$PATH:/Users/bigtyme/Dropbox/Programs/system-scripts
# export PYTHONPATH=$PYTHONPATH:/Users/bigtyme/Google-dr/Research/Model
# export PATH=/Users/bigtyme/bin:/usr/local/bin:/usr/local/share/python:$PATH:/Users/bigtyme/Dropbox/Programs/system-scripts
# export PYTHONPATH=/usr/local/lib/python2.7/site-packages:/usr/local/lib/python3.5/site-packages:$PYTHONPATH
# To get autojump working (replaced by fasd (brew install and added to plugins))
# [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/bigtyme/Programs/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/bigtyme/Programs/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/bigtyme/Programs/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/bigtyme/Programs/google-cloud-sdk/completion.zsh.inc'; fi

# This is maybe needed for R to work properly but think for windows
# Sys.setlocale(category="LC_ALL", locale = "en_US.UTF-8")
