#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

expand-or-complete-with-dots() {      # This bunch of code displays red dots when autocompleting
  echo -n "\e[31m......\e[0m"         # a command with the tab key, "Oh-my-zsh"-style.
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

#function f() { find . -iname "*$1*" ${@:2} }
#function r() { grep "$1" ${@:2} -R . }

setopt extended_glob
setopt ksh_glob

# Source private.
if [[ -s "${HOME}/.zprivate" ]]; then
  source "${HOME}/.zprivate"
fi

if [[ -s "${HOME}/.zaliases" ]]; then
  source "${HOME}/.zaliases"
fi

# Try to setup to expand aliases
expand-aliases() {
  unset 'functions[_expand-aliases]'
  functions[_expand-aliases]=$BUFFER
  (($+functions[_expand-aliases])) &&
	BUFFER=${functions[_expand-aliases]#$'\t'} &&
	CURSOR=$#BUFFER
}
zle -N expand-aliases
bindkey '\e^E' expand-aliases

# Treat these characters as part of a word.
WORDCHARS='*?[]~&;!#$%^(){}<>'

# Setup basic paths
export PATH=${HOME}/bin:$PATH
export LD_LIBRARY_PATH=${HOME}/lib:$LD_LIBRARY_PATH

# Mac config

export SUBLIME=subl
export EDITOR=$SUBLIME' -w'
export VISUAL=$EDITOR
# export NVM_DIR="$HOME/.nvm"
# . "/usr/local/opt/nvm/nvm.sh"

# export PATH=${HOME}/anaconda/bin:${HOME}/bin:/usr/local/bin:/usr/local/share/python:$PATH:${HOME}/Dropbox/Programs/system-scripts
export PATH=$HOME/bin:/usr/local/bin:$PATH:$HOME/Dropbox/Programs/system-scripts
# export PYTHONPATH=$PYTHONPATH:$HOME/Google-dr/Research/Model
# export PATH=$HOME/bin:/usr/local/bin:/usr/local/share/python:$PATH:$HOME/Dropbox/Programs/system-scripts
source "${HOME}/.zshrc_hidden"

# export PYTHONPATH=/usr/local/lib/python2.7/site-packages:/usr/local/lib/python3.5/site-packages:$PYTHONPATH
# To get autojump working (replaced by fasd (brew install and added to plugins))
# [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

eval "$(rbenv init -)"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '${HOME}/Programs/google-cloud-sdk/path.zsh.inc' ]; then source '${HOME}/Programs/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '${HOME}/Programs/google-cloud-sdk/completion.zsh.inc' ]; then source '${HOME}/Programs/google-cloud-sdk/completion.zsh.inc'; fi

. ${HOME}/anaconda/etc/profile.d/conda.sh
conda activate fastai2

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true
